# Test Runner for Linux
  name: TestLinux
  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

    workflow_dispatch:

  jobs:    
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-20.04

      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        
        - name: Install Skia Deps
          run: skia_deps_linux.sh

        - name: Run Tests
          run: bazel test ...
